#!/usr/bin/env Rscript
################################################################################
# eQTL and trQTL DRS-seq replication in short-read RNA-seq (Illumina 317 LCL samples)
################################################################################
# Description: Test replication of long-read QTL discoveries (nanopore DRS) in the
#              bigger short-read RNA-seq cohort (Illumina).
#
# Approach:
#   1. Identify overlapping genes tested in both datasets
#   2. Extract nominal p-values for matched gene-SNP pairs
#   3. Calculate FDR for replication cohort
#   4. Compare discovery rates between technologies
#
# Input:  - Short-read eQTL results (permutation + nominal)
#         - Long-read eQTL nominal results (filtered to significant Illumina gene-SNP pairs (eQTLs))
#         - Long-read trQTL nominal results (filtered to significant Illumina gene-SNP pairs (eQTLs)
#           and keep all transcripts)
#
# Input File Generation:
#   longread_eQTL_filtered_to_shortread_eGenes.txt.gz was generated by filtering
#   nanopore eQTL nominal results to gene-SNP pairs from significant Illumina eQTLs:
#
#   awk '{gene=$1; sub(/\..*/,"",gene); print gene"\t"$8}' \
#     shortread_eQTLs_significant.txt | sort -u > illumina_egene_snp_pairs.txt
#
#   zcat nanopore_eQTL_all_nominal.txt.gz | \
#     awk 'NR==FNR{pairs[$1"\t"$2]=1; next} \
#          {gene=$6; sub(/\..*/,"",gene); snp=$10; \
#           if((gene"\t"snp) in pairs) print $6,snp,$14,$14}' \
#       illumina_egene_snp_pairs.txt - | \
#     gzip > longread_eQTL_filtered_to_shortread_eGenes.txt.gz
#
# Output: - Replicated eQTLs and trQTLs at FDR < 5%
#         - P-value and q-value distributions
#         - Venn diagrams showing overlap
#         - Summary statistics
#
# Dependencies: R (data.table, qvalue, VennDiagram)
################################################################################

library(data.table)
library(qvalue)
library(VennDiagram)

# Configuration
FDR_THRESHOLD <- 0.05

# Create output directories
dir.create("results", showWarnings = FALSE, recursive = TRUE)
dir.create("plots", showWarnings = FALSE, recursive = TRUE)

cat("\n")
cat("======================================================================\n")
cat("eQTL and trQTL Replication Analysis\n")
cat("Long-read (nanopore) → Short-read (Illumina)\n")
cat("======================================================================\n")
cat("FDR threshold:", FDR_THRESHOLD, "\n\n")

################################################################################
# PART 1: LOAD SHORT-READ EQTL RESULTS (DISCOVERY COHORT)
################################################################################

cat("PART 1: Loading short-read (Illumina) eQTL results - DISCOVERY\n")
cat("----------------------------------------------------------------------\n")

# Load Illumina permutation results (significant eQTLs)
shortread_eqtls <- fread("shortread_eQTLs_significant.txt")

cat("  ✓ Loaded:", nrow(shortread_eqtls), "eGenes\n")

# Clean gene IDs (remove version numbers)
shortread_eqtls$gene_id <- sub("\\..*", "", shortread_eqtls$V1)

cat("  ✓ Gene IDs cleaned\n\n")

################################################################################
# PART 2: LOAD LONG-READ EQTL RESULTS (REPLICATION COHORT)
################################################################################

cat("PART 2: Loading long-read (nanopore) eQTL results - REPLICATION\n")
cat("----------------------------------------------------------------------\n")

# Load nanopore eQTL nominal results filtered to Illumina eGene-SNP pairs
longread_eqtls <- fread("longread_eQTL_filtered_to_shortread_eGenes.txt.gz",
                        fill = TRUE)

cat("  ✓ Raw data loaded:", nrow(longread_eqtls), "rows\n")

# Fix column structure (remove extra first column if present)
if (ncol(longread_eqtls) == 5) {
  longread_eqtls <- longread_eqtls[, -1]
  cat("  ✓ Removed extra index column\n")
}

# Set column names
setnames(longread_eqtls, c("gene", "SNP", "FDR_pvalue", "nominal_pvalue"))

# Clean gene IDs
longread_eqtls$gene_id <- sub("\\..*", "", longread_eqtls$gene)

cat("  ✓ Processed:", nrow(longread_eqtls), "gene-SNP pairs\n")
cat("  ✓ Unique genes:", uniqueN(longread_eqtls$gene_id), "\n")

# Save intermediate file
fwrite(longread_eqtls,
       "results/longread_eQTL_gene_SNP_pairs_cleaned.txt",
       sep = "\t")

cat("\n")

################################################################################
# DIAGNOSTIC: Verify filtering strategy
################################################################################

cat("DIAGNOSTIC: Verifying input file filtering\n")
cat("----------------------------------------------------------------------\n")

# Check gene overlap
genes_shortread <- unique(shortread_eqtls$gene_id)
genes_longread_eqtl <- unique(longread_eqtls$gene_id)
gene_overlap <- length(intersect(genes_shortread, genes_longread_eqtl))
gene_overlap_pct <- round(100 * gene_overlap / length(genes_longread_eqtl), 1)

cat("  Genes:\n")
cat("    Short-read (discovery eGenes):", length(genes_shortread), "\n")
cat("    Long-read file:", length(genes_longread_eqtl), "\n")
cat("    Overlap:", gene_overlap, "(", gene_overlap_pct, "%)\n\n")

# Check SNP overlap
snps_shortread <- unique(shortread_eqtls$V8)
snps_longread <- unique(longread_eqtls$SNP)
snp_overlap <- length(intersect(snps_shortread, snps_longread))
snp_overlap_pct <- round(100 * snp_overlap / length(snps_longread), 1)

cat("  SNPs:\n")
cat("    Short-read (tested):", length(snps_shortread), "\n")
cat("    Long-read file:", length(snps_longread), "\n")
cat("    Overlap:", snp_overlap, "(", snp_overlap_pct, "%)\n\n")

# Interpret filtering strategy
if (gene_overlap_pct >= 95 && snp_overlap_pct >= 95) {
  cat("  ✓ CONFIRMED: Filtered by BOTH genes AND SNPs\n")
  cat("    → Optimal for replication analysis\n\n")
  filtering_strategy <- "both"
} else if (gene_overlap_pct >= 95) {
  cat("  ⚠ Filtered by genes only\n\n")
  filtering_strategy <- "genes_only"
} else if (snp_overlap_pct >= 95) {
  cat("  ⚠ Filtered by SNPs only\n\n")
  filtering_strategy <- "snps_only"
} else {
  cat("  ⚠ WARNING: Incomplete filtering detected\n\n")
  filtering_strategy <- "mixed"
}

# Save diagnostic info
diagnostic_info <- data.table(
  Metric = c("Shortread_discovery_genes", "Longread_replication_genes",
             "Gene_overlap", "Gene_overlap_pct",
             "Shortread_SNPs", "Longread_SNPs",
             "SNP_overlap", "SNP_overlap_pct",
             "Filtering_strategy"),
  Value = c(length(genes_shortread), length(genes_longread_eqtl),
            gene_overlap, gene_overlap_pct,
            length(snps_shortread), length(snps_longread),
            snp_overlap, snp_overlap_pct,
            filtering_strategy)
)

fwrite(diagnostic_info, "results/00_input_filtering_diagnostic.txt", sep = "\t")

################################################################################
# PART 3: LOAD LONG-READ trQTL RESULTS (TRANSCRIPT-LEVEL)
################################################################################

cat("PART 3: Loading long-read (nanopore) trQTL results - TRANSCRIPT-LEVEL\n")
cat("----------------------------------------------------------------------\n")

# Create gene-SNP pairs from short-read results for reference
shortread_gene_snp_pairs <- shortread_eqtls[, .(gene = gene_id, snp_id = V8)]

# Save pairs (for external filtering if needed)
fwrite(shortread_gene_snp_pairs,
       "results/shortread_eGene_SNP_pairs_for_filtering.txt",
       sep = "\t", col.names = FALSE)

# Load filtered nanopore trQTL nominal results
trqtl_files <- list.files("longread_trQTL_filtered_nominals",
                          pattern = "_filtered\\.txt$",
                          full.names = TRUE)

if (length(trqtl_files) == 0) {
  cat("  ⚠ WARNING: No filtered trQTL files found\n")
  cat("  ⚠ Skipping trQTL analysis\n")
  cat("  ⚠ Expected directory: longread_trQTL_filtered_nominals/\n")
  cat("  ⚠ Expected files: chr*_filtered.txt\n\n")

  longread_trqtls <- data.table()
  skip_trqtl <- TRUE

} else {

  cat("  ✓ Found", length(trqtl_files), "filtered trQTL files\n")

  # Load and combine all files
  longread_trqtls <- rbindlist(lapply(trqtl_files, fread), use.names = FALSE)

  # Set column names (QTLtools nominal output format)
  setnames(longread_trqtls,
           c("grp_id", "phe_chr", "phe_from", "phe_to", "phe_strd",
             "phe_id", "n_phe_in_grp", "n_var_in_cis", "dist_phe_var",
             "var_id", "var_chr", "var_from", "var_to",
             "pval_nominal", "r_squared", "slope", "best_hit"))

  # Clean gene IDs
  longread_trqtls$gene_id <- sub("\\..*", "", longread_trqtls$grp_id)

  cat("  ✓ Loaded:", nrow(longread_trqtls), "transcript-SNP pairs\n")
  cat("  ✓ Unique genes:", uniqueN(longread_trqtls$gene_id), "\n")
  cat("  ✓ Unique transcripts:", uniqueN(longread_trqtls$phe_id), "\n")

  # Save summary
  fwrite(longread_trqtls[, .(gene_id, phe_id, var_id, pval_nominal)],
         "results/longread_trQTL_transcript_SNP_pairs_cleaned.txt",
         sep = "\t")

  skip_trqtl <- FALSE
}

cat("\n")

################################################################################
# PART 4: IDENTIFY COMMON GENES FOR REPLICATION
################################################################################

cat("PART 4: Identifying common genes across datasets\n")
cat("----------------------------------------------------------------------\n")

# Get gene sets
genes_shortread <- unique(shortread_eqtls$gene_id)
genes_longread_eqtl <- unique(longread_eqtls$gene_id)

cat("  Short-read eQTL genes (discovery):", length(genes_shortread), "\n")
cat("  Long-read eQTL genes (replication):", length(genes_longread_eqtl), "\n")

if (!skip_trqtl) {
  genes_longread_trqtl <- unique(longread_trqtls$gene_id)
  cat("  Long-read trQTL genes (replication):", length(genes_longread_trqtl), "\n")

  # Genes tested in both long-read assays
  genes_common_longread <- intersect(genes_longread_eqtl, genes_longread_trqtl)
  cat("  Overlap (long-read eQTL ∩ trQTL):", length(genes_common_longread), "\n")

  # Filter short-read to genes tested in both long-read assays
  shortread_eqtls_filtered <- shortread_eqtls[gene_id %in% genes_common_longread]

} else {
  # If no trQTL data, just use eQTL overlap
  genes_common_longread <- genes_longread_eqtl
  shortread_eqtls_filtered <- shortread_eqtls[gene_id %in% genes_longread_eqtl]
}

cat("  Short-read eQTLs (filtered for replication):",
    nrow(shortread_eqtls_filtered), "\n")

# Save filtered set
fwrite(shortread_eqtls_filtered,
       "results/01_shortread_eQTLs_filtered_for_replication.txt",
       sep = "\t")

cat("\n")

################################################################################
# PART 5: eQTL REPLICATION ANALYSIS
################################################################################

cat("PART 5: eQTL replication analysis (gene-level)\n")
cat("----------------------------------------------------------------------\n")

# Filter long-read eQTLs to genes in filtered short-read set
eqtl_replication_set <- longread_eqtls[gene_id %in% shortread_eqtls_filtered$gene_id]

cat("  Gene-SNP pairs tested:", nrow(eqtl_replication_set), "\n")
cat("  Unique genes tested:", uniqueN(eqtl_replication_set$gene_id), "\n\n")

# Calculate q-values
cat("  Calculating FDR (q-values)...\n")

qobj_eqtl <- qvalue(p = eqtl_replication_set$nominal_pvalue,
                    fdr.level = FDR_THRESHOLD)

cat("\n  === eQTL Replication Summary ===\n")
cat("  π₀ (proportion of true nulls):", round(qobj_eqtl$pi0, 3), "\n")
cat("  π₁ (proportion of true signals):", round(1 - qobj_eqtl$pi0, 3), "\n\n")

print(summary(qobj_eqtl))

# Extract significant eQTLs
eqtl_replicated <- eqtl_replication_set[qobj_eqtl$significant == TRUE]
eqtl_replicated$qvalue <- qobj_eqtl$qvalues[qobj_eqtl$significant == TRUE]

cat("\n  ✓ Replicated eQTLs (FDR <", FDR_THRESHOLD, "):",
    nrow(eqtl_replicated), "\n")
cat("  ✓ Unique replicated genes:", uniqueN(eqtl_replicated$gene_id), "\n")
cat("  ✓ Replication rate:",
    round(100 * nrow(eqtl_replicated) / nrow(eqtl_replication_set), 1), "%\n")

# Save results
fwrite(eqtl_replicated,
       sprintf("results/02_longread_eQTLs_replicated_FDR%.0f.txt",
               FDR_THRESHOLD*100),
       sep = "\t")

cat("\n")

################################################################################
# PART 6: trQTL REPLICATION ANALYSIS
################################################################################

if (!skip_trqtl) {

  cat("PART 6: trQTL replication analysis (transcript-level)\n")
  cat("----------------------------------------------------------------------\n")

  # Filter to genes in filtered short-read set
  trqtl_replication_set <- longread_trqtls[
    gene_id %in% shortread_eqtls_filtered$gene_id,
    .(gene_id, phe_id, pval_nominal)
  ]

  cat("  Transcript-SNP pairs tested:", nrow(trqtl_replication_set), "\n")
  cat("  Unique genes:", uniqueN(trqtl_replication_set$gene_id), "\n")
  cat("  Unique transcripts:", uniqueN(trqtl_replication_set$phe_id), "\n\n")

  # ========================================================================
  # Approach 1: Minimum p-value per gene (conservative)
  # ========================================================================

  cat("  Approach 1: Minimum p-value per gene (conservative)\n")
  cat("  Tests if ANY transcript shows genetic signal\n\n")

  trqtl_min_pval_per_gene <- trqtl_replication_set[
    , .(min_pval = min(pval_nominal, na.rm = TRUE)),
    by = gene_id
  ]

  # Calculate q-values
  qobj_trQTL_min <- qvalue(p = trqtl_min_pval_per_gene$min_pval,
                           fdr.level = FDR_THRESHOLD)

  cat("    π₀:", round(qobj_trQTL_min$pi0, 3), "\n")
  cat("    π₁:", round(1 - qobj_trQTL_min$pi0, 3), "\n\n")

  print(summary(qobj_trQTL_min))

  trqtl_replicated_by_gene <- trqtl_min_pval_per_gene[qobj_trQTL_min$significant == TRUE]
  trqtl_replicated_by_gene$qvalue <- qobj_trQTL_min$qvalues[qobj_trQTL_min$significant == TRUE]

  cat("\n    ✓ Replicated genes:", nrow(trqtl_replicated_by_gene), "\n")
  cat("    ✓ Replication rate:",
      round(100 * nrow(trqtl_replicated_by_gene) / nrow(trqtl_min_pval_per_gene), 1),
      "%\n\n")

  fwrite(trqtl_replicated_by_gene,
         sprintf("results/03_longread_trQTLs_replicated_by_gene_FDR%.0f.txt",
                 FDR_THRESHOLD*100),
         sep = "\t")

  # ========================================================================
  # Approach 2: All transcript-SNP pairs (liberal)
  # ========================================================================

  cat("  Approach 2: All transcript-SNP pairs (liberal)\n")
  cat("  Tests each transcript independently\n\n")

  # Calculate q-values for all pairs
  qobj_trQTL_all <- qvalue(p = trqtl_replication_set$pval_nominal,
                           fdr.level = FDR_THRESHOLD)

  cat("    π₀:", round(qobj_trQTL_all$pi0, 3), "\n")
  cat("    π₁:", round(1 - qobj_trQTL_all$pi0, 3), "\n\n")

  print(summary(qobj_trQTL_all))

  trqtl_replicated_by_transcript <- trqtl_replication_set[qobj_trQTL_all$significant == TRUE]
  trqtl_replicated_by_transcript$qvalue <- qobj_trQTL_all$qvalues[qobj_trQTL_all$significant == TRUE]

  cat("\n    ✓ Replicated transcript-SNP pairs:",
      nrow(trqtl_replicated_by_transcript), "\n")
  cat("    ✓ Unique genes:", uniqueN(trqtl_replicated_by_transcript$gene_id), "\n")
  cat("    ✓ Unique transcripts:", uniqueN(trqtl_replicated_by_transcript$phe_id), "\n\n")

  fwrite(trqtl_replicated_by_transcript,
         sprintf("results/04_longread_trQTLs_replicated_by_transcript_FDR%.0f.txt",
                 FDR_THRESHOLD*100),
         sep = "\t")

} else {
  cat("PART 6: Skipping trQTL replication (no data)\n\n")
}

cat("\n")

################################################################################
# PART 7: GENERATE PLOTS
################################################################################

cat("PART 7: Generating plots\n")
cat("----------------------------------------------------------------------\n")

cat("  Creating eQTL replication plots...\n")

# Colorblind-friendly palette
color_eqtl <- "#0072B2"    # Blue
color_qval <- "#E69F00"    # Orange
color_sig <- "#D55E00"     # Red

# P-value histogram
pdf("plots/01_eQTL_replication_pvalue_histogram.pdf", width = 8, height = 6)
hist(eqtl_replication_set$nominal_pvalue,
     breaks = 50,
     col = color_eqtl,
     border = "white",
     main = "Long-read eQTL Replication: Nominal P-values",
     xlab = "Nominal P-value",
     ylab = "Frequency")
dev.off()

# Q-value histogram
pdf("plots/02_eQTL_replication_qvalue_histogram.pdf", width = 8, height = 6)
hist(qobj_eqtl$qvalues,
     breaks = 50,
     col = color_qval,
     border = "white",
     main = "Long-read eQTL Replication: Q-values",
     xlab = "Q-value",
     ylab = "Frequency")
dev.off()

# P-value vs Q-value scatter
pdf("plots/03_eQTL_replication_pvalue_vs_qvalue.pdf", width = 8, height = 7)
plot(eqtl_replication_set$nominal_pvalue,
     qobj_eqtl$qvalues,
     pch = 19,
     cex = 0.6,
     col = rgb(0, 0.45, 0.7, 0.4),
     xlab = "Nominal P-value",
     ylab = "Q-value",
     main = sprintf("Long-read eQTL Replication (π₁ = %.3f)", 1 - qobj_eqtl$pi0))
abline(h = FDR_THRESHOLD, col = color_sig, lwd = 2, lty = 2)
legend("topright", legend = sprintf("FDR < %.2f", FDR_THRESHOLD),
       col = color_sig, lty = 2, lwd = 2, bty = "n")
dev.off()

if (!skip_trqtl) {

  cat("  Creating trQTL replication plots...\n")

  color_trqtl_min <- "#CC79A7"  # Purple
  color_trqtl_all <- "#009E73"  # Teal

  # Minimum p-value histogram
  pdf("plots/04_trQTL_replication_min_pvalue_histogram.pdf", width = 8, height = 7)
  hist(trqtl_min_pval_per_gene$min_pval,
       breaks = 50,
       col = color_trqtl_min,
       border = "white",
       main = "Long-read trQTL Replication: Minimum P-value per Gene",
       xlab = "Minimum P-value",
       ylab = "Frequency")
  dev.off()

  # All p-values histogram
  pdf("plots/05_trQTL_replication_all_pvalue_histogram.pdf", width = 8, height = 7)
  hist(trqtl_replication_set$pval_nominal,
       breaks = 50,
       col = color_trqtl_all,
       border = "white",
       main = "Long-read trQTL Replication: All Transcript P-values",
       xlab = "Nominal P-value",
       ylab = "Frequency")
  dev.off()
}

cat("  ✓ Plots saved to plots/\n\n")

################################################################################
# PART 8: VENN DIAGRAM
################################################################################

if (!skip_trqtl) {

  cat("PART 8: Creating Venn diagram of gene overlap\n")
  cat("----------------------------------------------------------------------\n")

  # Extract unique gene sets
  genes_trqtl_replicated <- unique(trqtl_replicated_by_transcript$gene_id)
  genes_eqtl_longread_replicated <- unique(eqtl_replicated$gene_id)
  genes_eqtl_shortread_discovery <- unique(shortread_eqtls_filtered$gene_id)

  # Calculate overlaps
  overlap_trqtl_eqtl_longread <- length(intersect(
    genes_trqtl_replicated,
    genes_eqtl_longread_replicated
  ))

  overlap_trqtl_eqtl_shortread <- length(intersect(
    genes_trqtl_replicated,
    genes_eqtl_shortread_discovery
  ))

  overlap_eqtl_longread_shortread <- length(intersect(
    genes_eqtl_longread_replicated,
    genes_eqtl_shortread_discovery
  ))

  overlap_all_three <- length(Reduce(intersect, list(
    genes_trqtl_replicated,
    genes_eqtl_longread_replicated,
    genes_eqtl_shortread_discovery
  )))

  cat("  trQTL genes (long-read, replicated):",
      length(genes_trqtl_replicated), "\n")
  cat("  eQTL genes (long-read, replicated):",
      length(genes_eqtl_longread_replicated), "\n")
  cat("  eQTL genes (short-read, discovery):",
      length(genes_eqtl_shortread_discovery), "\n\n")

  cat("  Overlaps:\n")
  cat("    trQTL ∩ eQTL (long-read):", overlap_trqtl_eqtl_longread, "\n")
  cat("    trQTL ∩ eQTL (short-read):", overlap_trqtl_eqtl_shortread, "\n")
  cat("    eQTL (long-read) ∩ eQTL (short-read):",
      overlap_eqtl_longread_shortread, "\n")
  cat("    All three:", overlap_all_three, "\n\n")

  # Create Venn diagram (colorblind-friendly colors)
  venn_plot <- venn.diagram(
    x = list(
      "trQTL\n(long-read)" = genes_trqtl_replicated,
      "eQTL\n(long-read)" = genes_eqtl_longread_replicated,
      "eQTL\n(short-read)" = genes_eqtl_shortread_discovery
    ),
    filename = NULL,
    fill = c("#E69F00", "#0072B2", "#009E73"),
    alpha = 0.5,
    cex = 1.5,
    cat.cex = 1.3,
    cat.fontface = "bold",
    lwd = 2,
    main = "QTL Discovery Overlap Across Technologies",
    main.cex = 1.5
  )

  pdf("plots/06_venn_diagram_qtl_gene_overlap.pdf", width = 10, height = 8)
  grid::grid.newpage()
  grid::grid.draw(venn_plot)
  dev.off()

  cat("  ✓ Venn diagram saved\n\n")
}

################################################################################
# PART 9: SUMMARY STATISTICS
################################################################################

cat("PART 9: Writing summary statistics\n")
cat("----------------------------------------------------------------------\n")

# Build summary table
summary_stats <- data.table(
  Dataset = c(
    "Short-read eQTLs (discovery, total)",
    "Short-read eQTLs (filtered for replication)",
    "Long-read eQTLs (tested in replication)",
    "Long-read eQTLs (replicated at FDR<5%)",
    "eQTL replication rate (%)"
  ),
  Count = c(
    nrow(shortread_eqtls),
    nrow(shortread_eqtls_filtered),
    nrow(eqtl_replication_set),
    nrow(eqtl_replicated),
    round(100 * nrow(eqtl_replicated) / nrow(eqtl_replication_set), 1)
  )
)

if (!skip_trqtl) {
  summary_stats <- rbind(summary_stats, data.table(
    Dataset = c(
      "Long-read trQTLs (genes tested in replication)",
      "Long-read trQTLs (replicated genes, min p-value)",
      "Long-read trQTLs (replicated genes, all transcripts)",
      "trQTL gene replication rate - min p (%)",
      "trQTL ∩ eQTL (long-read)",
      "All three datasets (trQTL + 2 eQTLs)"
    ),
    Count = c(
      uniqueN(trqtl_replication_set$gene_id),
      nrow(trqtl_replicated_by_gene),
      uniqueN(trqtl_replicated_by_transcript$gene_id),
      round(100 * nrow(trqtl_replicated_by_gene) / nrow(trqtl_min_pval_per_gene), 1),
      overlap_trqtl_eqtl_longread,
      overlap_all_three
    )
  ))
}

fwrite(summary_stats, "results/99_replication_summary_statistics.txt", sep = "\t")

print(summary_stats)

cat("\n")

################################################################################
# FINAL SUMMARY
################################################################################

cat("======================================================================\n")
cat("Replication Analysis Complete!\n")
cat("======================================================================\n\n")

cat("Input file validation:\n")
cat("  ✓ Filtering strategy:", filtering_strategy, "\n")
cat("  ✓ Gene overlap:", gene_overlap_pct, "%\n")
cat("  ✓ SNP overlap:", snp_overlap_pct, "%\n\n")

cat("Output files:\n")
cat("  results/00_input_filtering_diagnostic.txt\n")
cat("  results/01_shortread_eQTLs_filtered_for_replication.txt\n")
cat("  results/02_longread_eQTLs_replicated_FDR5.txt\n")
if (!skip_trqtl) {
  cat("  results/03_longread_trQTLs_replicated_by_gene_FDR5.txt\n")
  cat("  results/04_longread_trQTLs_replicated_by_transcript_FDR5.txt\n")
}
cat("  results/99_replication_summary_statistics.txt\n")
cat("  plots/01-06_*.pdf\n\n")

cat("Key findings:\n")
cat("  • eQTL replication rate:",
    round(100 * nrow(eqtl_replicated) / nrow(eqtl_replication_set), 1), "%\n")
cat("  • π₁ (true signals in long-read eQTLs):",
    round(1 - qobj_eqtl$pi0, 3), "\n")

if (!skip_trqtl) {
  cat("  • trQTL replicated genes (min p):", nrow(trqtl_replicated_by_gene), "\n")
  cat("  • trQTL replicated genes (all transcripts):",
      uniqueN(trqtl_replicated_by_transcript$gene_id), "\n")
  cat("  • Genes with both eQTL + trQTL:", overlap_trqtl_eqtl_longread, "\n")
}

cat("\n✓ Analysis complete!\n\n")
